using System;
using System.Collections;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using CesiumForUnity;
using UnityEngine;
using UnityEngine.Networking;
#if UNITY_EDITOR
using UnityEditor;
#endif

namespace Rugem.RoadTools
{
    public enum TerrainSourceMode
    {
        CesiumIon,
        CustomUrl,
        Ellipsoid,
        DemServer,
    }

    public enum DemUploadStatus
    {
        Idle,
        Uploading,
        Processing,
        Completed,
        Failed,
    }

    [AddComponentMenu("RoadTools/Terrain Source Switcher")]
    public class TerrainSourceSwitcher : MonoBehaviour
    {
        [Header("Cesium3DTileset")]
        [SerializeField] private Cesium3DTileset _tileset;

        [Header("Startup Mode")]
        [SerializeField] private TerrainSourceMode _mode = TerrainSourceMode.CesiumIon;

        [Tooltip("If enabled, the selected terrain source is applied automatically when Play Mode starts.")]
        [SerializeField] private bool _applyOnStart = false;

        [Header("Cesium Ion")]
        [Tooltip("Cesium Ion Asset ID. Cesium World Terrain is 1.")]
        [SerializeField] private long _ionAssetId = 1;

        [Header("Custom Terrain URL")]
        [Tooltip("Full quantized-mesh layer.json URL. Example: http://localhost:5001/layer.json")]
        [SerializeField] private string _terrainUrl = "http://localhost:5001/layer.json";

        [Header("Docker DEM Server")]
        [Tooltip("Tiler server base URL. Example: http://localhost:8000")]
        [SerializeField] private string _demServerUrl = "http://localhost:8000";

        [Tooltip("DEM file path used when uploading in Play Mode.")]
        [SerializeField] private string _demFilePath = "";

        [Tooltip("Maximum terrain zoom generated by the Docker server.")]
        [SerializeField] [Range(6, 16)] private int _demMaxZoom = 12;

        [Tooltip("Completed Docker terrain job id. If set, Edit Mode uses /terrain/<job_id>/layer.json.")]
        [SerializeField] private string _demJobId = "";

        [Header("Terrain Loading Limits")]
        [Tooltip("Apply conservative Cesium loading settings when using a local terrain URL.")]
        [SerializeField] private bool _applyTerrainLoadingLimits = true;

        [Tooltip("Higher values request fewer terrain tiles. For quantized-mesh, this is effectively divided by 8.")]
        [SerializeField] [Range(16f, 128f)] private float _terrainMaximumScreenSpaceError = 32f;

        [Tooltip("Maximum terrain tile requests processed at the same time.")]
        [SerializeField] [Range(1, 20)] private int _terrainMaximumSimultaneousTileLoads = 6;

        [Tooltip("Cesium terrain cache budget for this tileset, in MB.")]
        [SerializeField] [Range(0, 1024)] private int _terrainMaximumCachedMegabytes = 128;

        [Tooltip("Lower values prevent large bursts of descendant terrain tiles.")]
        [SerializeField] [Range(0, 50)] private int _terrainLoadingDescendantLimit = 8;

        [Header("DEM Status")]
        [SerializeField] private DemUploadStatus _demStatus = DemUploadStatus.Idle;
        [SerializeField] [TextArea(2, 4)] private string _demStatusMessage = "";

        // 최대 폴링 횟수 (3초 간격 × 200 = 10분)
        private const long BytesPerMegabyte = 1024L * 1024L;
        private const int MaxPollCount = 200;
        private const string TerrainRequestCacheVersion = "terrain-v3";

        public TerrainSourceMode CurrentMode => _mode;
        public DemUploadStatus DemStatus => _demStatus;
        public string DemStatusMessage => _demStatusMessage;
        public string ResolvedTerrainUrl => ResolveTerrainUrl(_mode);

#if UNITY_EDITOR
        [InitializeOnLoadMethod]
        private static void RegisterPlayModeReset()
        {
            EditorApplication.playModeStateChanged += state =>
            {
                if (state != PlayModeStateChange.ExitingEditMode) return;
                // 도메인 리로드 전에 Cesium 네이티브 타일 로딩을 중단시켜 힙 손상 방지
                foreach (var sw in FindObjectsByType<TerrainSourceSwitcher>(FindObjectsSortMode.None))
                {
                    if (!sw._applyOnStart)
                        sw.PrepareTilesetForManualApply();
                }
            };
        }
#endif

#if UNITY_EDITOR
        private bool _editorUploadInProgress;
#endif

        private void Start()
        {
            if (_applyOnStart)
            {
                Apply(_mode);
                return;
            }

            PrepareTilesetForManualApply();
            Debug.Log("[TerrainSwitcher] Startup terrain loading is disabled. Use the inspector buttons to apply a terrain source.");
        }

        private void OnValidate()
        {
            // Do not start Cesium network loading from inspector validation.
            // Use the inspector buttons or Play Mode to apply a terrain source.
        }

        public void Apply(TerrainSourceMode mode)
        {
            if (_tileset == null)
            {
                Debug.LogError("[TerrainSwitcher] Target Cesium3DTileset is not assigned.");
                return;
            }

            _mode = mode;

#if UNITY_EDITOR
            if (!Application.isPlaying)
            {
                ApplyEditMode(mode);
                return;
            }
#endif

            switch (mode)
            {
                case TerrainSourceMode.CesiumIon:
                    ApplyIon();
                    Debug.Log($"[TerrainSwitcher] Cesium Ion mode. Asset ID: {_ionAssetId}");
                    break;

                case TerrainSourceMode.CustomUrl:
                    ApplyUrl(ResolveTerrainUrl(TerrainSourceMode.CustomUrl), "Terrain Url is empty.");
                    break;

                case TerrainSourceMode.Ellipsoid:
                    _tileset.tilesetSource = CesiumDataSource.FromEllipsoid;
                    Debug.Log("[TerrainSwitcher] Ellipsoid mode.");
                    break;

                case TerrainSourceMode.DemServer:
                    if (!string.IsNullOrWhiteSpace(_demFilePath))
                    {
                        _demStatus = DemUploadStatus.Idle;
                        StartCoroutine(UploadDemAndApply());
                        Debug.Log($"[TerrainSwitcher] DEM server upload started: {_demFilePath} -> {_demServerUrl}");
                        return;
                    }

                    string resolvedUrl = ResolveTerrainUrl(TerrainSourceMode.DemServer);
                    if (string.IsNullOrWhiteSpace(resolvedUrl))
                    {
                        Debug.LogError("[TerrainSwitcher] DEM file path is empty and no DEM server URL is available.");
                        return;
                    }

                    ApplyUrl(resolvedUrl, "DEM server URL is empty.");
                    break;
            }
        }

        public void SetCustomUrl(string url)
        {
            _terrainUrl = url;
            if (_mode == TerrainSourceMode.CustomUrl)
                Apply(TerrainSourceMode.CustomUrl);
        }

        public IEnumerator UploadDemAndApply()
        {
            _demStatus = DemUploadStatus.Uploading;
            _demStatusMessage = "Reading DEM file...";

            if (!File.Exists(_demFilePath))
            {
                SetFailed($"File not found: {_demFilePath}");
                yield break;
            }

            // 파일 읽기를 백그라운드 스레드에서 수행해 메인 스레드 블로킹 방지
            byte[] fileBytes = null;
            Exception readException = null;
            var readTask = Task.Run(() => File.ReadAllBytes(_demFilePath));
            while (!readTask.IsCompleted)
                yield return null;

            if (readTask.IsFaulted)
            {
                SetFailed($"File read failed: {readTask.Exception?.InnerException?.Message ?? readTask.Exception?.Message}");
                yield break;
            }
            fileBytes = readTask.Result;

            string fileName = Path.GetFileName(_demFilePath);
            string ext = Path.GetExtension(_demFilePath).ToLowerInvariant();
            string mime = ext is ".tif" or ".tiff" ? "image/tiff" : "application/octet-stream";

            _demStatusMessage = $"Uploading DEM ({fileBytes.Length / 1048576} MB)...";

            var form = new List<IMultipartFormSection>
            {
                new MultipartFormFileSection("demFile", fileBytes, fileName, mime),
                new MultipartFormDataSection("maxZoom", _demMaxZoom.ToString()),
            };

            string uploadUrl = TrimTrailingSlash(_demServerUrl) + "/api/terrain/upload";
            using (UnityWebRequest uploadReq = UnityWebRequest.Post(uploadUrl, form))
            {
                yield return uploadReq.SendWebRequest();

                if (uploadReq.result != UnityWebRequest.Result.Success)
                {
                    SetFailed($"Upload failed: {uploadReq.error}");
                    yield break;
                }

                UploadResponse uploadResp;
                try
                {
                    uploadResp = JsonUtility.FromJson<UploadResponse>(uploadReq.downloadHandler.text);
                }
                catch
                {
                    SetFailed("Failed to parse upload response.");
                    yield break;
                }

                _demJobId = uploadResp.jobId;
                _terrainUrl = BuildDemLayerUrl(_demJobId);
            }

            // 업로드 완료 후 파일 데이터 참조 해제
            fileBytes = null;
            form = null;

            _demStatus = DemUploadStatus.Processing;
            string statusUrl = TrimTrailingSlash(_demServerUrl) + $"/api/terrain/jobs/{_demJobId}/status";

            int pollCount = 0;
            while (pollCount < MaxPollCount)
            {
                yield return new WaitForSeconds(3f);
                pollCount++;

                using (UnityWebRequest req = UnityWebRequest.Get(statusUrl))
                {
                    yield return req.SendWebRequest();

                    if (req.result != UnityWebRequest.Result.Success)
                    {
                        _demStatusMessage = $"Checking status... ({req.error})";
                        continue;
                    }

                    StatusResponse sr;
                    try
                    {
                        sr = JsonUtility.FromJson<StatusResponse>(req.downloadHandler.text);
                    }
                    catch
                    {
                        continue;
                    }

                    _demStatusMessage = $"Processing: {sr.stage} ({sr.progress}%)";

                    if (sr.status == "completed")
                    {
                        _demStatus = DemUploadStatus.Completed;
                        _demStatusMessage = $"Completed. Tiles: {sr.tileCount}";
                        _terrainUrl = BuildDemLayerUrl(_demJobId);
                        ApplyUrl(_terrainUrl, "DEM layer URL is empty.");
                        Debug.Log($"[TerrainSwitcher] DEM terrain ready: {_terrainUrl}");
                        yield break;
                    }

                    if (sr.status == "failed")
                    {
                        SetFailed($"Server processing failed: {sr.error}");
                        yield break;
                    }
                }
            }

            SetFailed($"Timed out waiting for DEM processing after {MaxPollCount * 3}s.");
        }

#if UNITY_EDITOR
        private void ApplyEditMode(TerrainSourceMode mode)
        {
            switch (mode)
            {
                case TerrainSourceMode.CesiumIon:
                    ApplyIon();
                    break;

                case TerrainSourceMode.CustomUrl:
                    ApplyUrl(ResolveTerrainUrl(TerrainSourceMode.CustomUrl), "Terrain Url is empty.");
                    break;

                case TerrainSourceMode.Ellipsoid:
                    _tileset.tilesetSource = CesiumDataSource.FromEllipsoid;
                    break;

                case TerrainSourceMode.DemServer:
                    if (!string.IsNullOrWhiteSpace(_demFilePath))
                    {
                        UploadDemAndApplyInEditor();
                        break;
                    }

                    string demUrl = ResolveTerrainUrl(TerrainSourceMode.DemServer);
                    if (!string.IsNullOrWhiteSpace(demUrl))
                    {
                        ApplyUrl(demUrl, "DEM server URL is empty.");
                    }
                    else
                    {
                        Debug.LogWarning("[TerrainSwitcher] DEM file path is empty and no DEM server URL is available.");
                    }
                    break;
            }
        }

        public void UploadDemAndApplyInEditor()
        {
            if (_editorUploadInProgress)
            {
                Debug.LogWarning("[TerrainSwitcher] DEM upload is already running.");
                return;
            }

            _ = UploadDemAndApplyEditorAsync();
        }

        private async Task UploadDemAndApplyEditorAsync()
        {
            _editorUploadInProgress = true;
            try
            {
                _demStatus = DemUploadStatus.Uploading;
                _demStatusMessage = "Reading DEM file...";
                MarkEditorDirty();

                if (string.IsNullOrWhiteSpace(_demFilePath))
                {
                    SetFailed("DEM file path is empty.");
                    return;
                }

                if (!File.Exists(_demFilePath))
                {
                    SetFailed($"File not found: {_demFilePath}");
                    return;
                }

                byte[] fileBytes;
                try
                {
                    fileBytes = await Task.Run(() => File.ReadAllBytes(_demFilePath));
                }
                catch (Exception ex)
                {
                    SetFailed($"File read failed: {ex.Message}");
                    return;
                }

                string fileName = Path.GetFileName(_demFilePath);
                string ext = Path.GetExtension(_demFilePath).ToLowerInvariant();
                string mime = ext is ".tif" or ".tiff" ? "image/tiff" : "application/octet-stream";
                _demStatusMessage = $"Uploading DEM ({fileBytes.Length / 1048576} MB)...";
                MarkEditorDirty();

                var form = new List<IMultipartFormSection>
                {
                    new MultipartFormFileSection("demFile", fileBytes, fileName, mime),
                    new MultipartFormDataSection("maxZoom", _demMaxZoom.ToString()),
                };

                string uploadUrl = TrimTrailingSlash(_demServerUrl) + "/api/terrain/upload";
                using (UnityWebRequest uploadReq = UnityWebRequest.Post(uploadUrl, form))
                {
                    await SendEditorRequest(uploadReq);
                    if (uploadReq.result != UnityWebRequest.Result.Success)
                    {
                        SetFailed($"Upload failed: {uploadReq.error}");
                        return;
                    }

                    UploadResponse uploadResp;
                    try
                    {
                        uploadResp = JsonUtility.FromJson<UploadResponse>(uploadReq.downloadHandler.text);
                    }
                    catch
                    {
                        SetFailed("Failed to parse upload response.");
                        return;
                    }

                    if (string.IsNullOrWhiteSpace(uploadResp.jobId))
                    {
                        SetFailed("Upload response did not include jobId.");
                        return;
                    }

                    _demJobId = uploadResp.jobId;
                    _terrainUrl = BuildDemLayerUrl(_demJobId);
                    MarkEditorDirty();
                }

                _demStatus = DemUploadStatus.Processing;
                string statusUrl = TrimTrailingSlash(_demServerUrl) + $"/api/terrain/jobs/{_demJobId}/status";

                for (int pollCount = 0; pollCount < MaxPollCount; pollCount++)
                {
                    await Task.Delay(3000);

                    using UnityWebRequest req = UnityWebRequest.Get(statusUrl);
                    await SendEditorRequest(req);

                    if (req.result != UnityWebRequest.Result.Success)
                    {
                        _demStatusMessage = $"Checking status... ({req.error})";
                        MarkEditorDirty();
                        continue;
                    }

                    StatusResponse sr;
                    try
                    {
                        sr = JsonUtility.FromJson<StatusResponse>(req.downloadHandler.text);
                    }
                    catch
                    {
                        continue;
                    }

                    _demStatusMessage = $"Processing: {sr.stage} ({sr.progress}%)";
                    MarkEditorDirty();

                    if (sr.status == "completed")
                    {
                        _demStatus = DemUploadStatus.Completed;
                        _demStatusMessage = $"Completed. Tiles: {sr.tileCount}";
                        _terrainUrl = BuildDemLayerUrl(_demJobId);
                        ApplyUrl(_terrainUrl, "DEM layer URL is empty.");
                        MarkEditorDirty();
                        Debug.Log($"[TerrainSwitcher] DEM terrain ready: {_terrainUrl}");
                        return;
                    }

                    if (sr.status == "failed")
                    {
                        SetFailed($"Server processing failed: {sr.error}");
                        return;
                    }
                }

                SetFailed($"Timed out waiting for DEM processing after {MaxPollCount * 3}s.");
            }
            finally
            {
                _editorUploadInProgress = false;
                MarkEditorDirty();
            }
        }

        private static async Task SendEditorRequest(UnityWebRequest request)
        {
            UnityWebRequestAsyncOperation op = request.SendWebRequest();
            while (!op.isDone)
                await Task.Delay(100);
        }

        private void MarkEditorDirty()
        {
            EditorUtility.SetDirty(this);
            if (!Application.isPlaying)
                EditorApplication.QueuePlayerLoopUpdate();
        }
#endif

        private void ApplyIon()
        {
            _tileset.tilesetSource = CesiumDataSource.FromCesiumIon;
            _tileset.ionAssetID = _ionAssetId;
        }

        private void ApplyUrl(string url, string emptyMessage)
        {
            if (string.IsNullOrWhiteSpace(url))
            {
                Debug.LogWarning($"[TerrainSwitcher] {emptyMessage}");
                return;
            }

            ApplyTerrainLoadingLimits();

            if (_tileset.tilesetSource == CesiumDataSource.FromUrl &&
                string.Equals(_tileset.url, url, StringComparison.Ordinal))
            {
                Debug.Log($"[TerrainSwitcher] Terrain URL already active: {url}");
                return;
            }

            if (!string.Equals(_tileset.url, url, StringComparison.Ordinal))
                _tileset.url = url;

            if (_tileset.tilesetSource != CesiumDataSource.FromUrl)
                _tileset.tilesetSource = CesiumDataSource.FromUrl;

            Debug.Log($"[TerrainSwitcher] Terrain URL mode: {url}");
        }

        private void ApplyTerrainLoadingLimits()
        {
            if (!_applyTerrainLoadingLimits || _tileset == null)
                return;

            _tileset.suspendUpdate = false;
#if UNITY_EDITOR
            if (!Application.isPlaying)
                _tileset.updateInEditor = true;
#endif

            long cacheBytes = Math.Max(0, _terrainMaximumCachedMegabytes) * BytesPerMegabyte;
            uint maxLoads = (uint)Mathf.Max(1, _terrainMaximumSimultaneousTileLoads);
            uint descendantLimit = (uint)Mathf.Max(0, _terrainLoadingDescendantLimit);

            if (_tileset.preloadAncestors)
                _tileset.preloadAncestors = false;
            if (_tileset.preloadSiblings)
                _tileset.preloadSiblings = false;
            if (!Mathf.Approximately(_tileset.maximumScreenSpaceError, _terrainMaximumScreenSpaceError))
                _tileset.maximumScreenSpaceError = _terrainMaximumScreenSpaceError;
            if (_tileset.maximumSimultaneousTileLoads != maxLoads)
                _tileset.maximumSimultaneousTileLoads = maxLoads;
            if (_tileset.maximumCachedBytes != cacheBytes)
                _tileset.maximumCachedBytes = cacheBytes;
            if (_tileset.loadingDescendantLimit != descendantLimit)
                _tileset.loadingDescendantLimit = descendantLimit;
        }

        private void PrepareTilesetForManualApply()
        {
            if (_tileset == null)
                return;

            _tileset.suspendUpdate = true;
#if UNITY_EDITOR
            _tileset.updateInEditor = false;
#endif
            if (_tileset.tilesetSource != CesiumDataSource.FromEllipsoid)
                _tileset.tilesetSource = CesiumDataSource.FromEllipsoid;
        }

        private string ResolveTerrainUrl(TerrainSourceMode mode)
        {
            if (mode == TerrainSourceMode.DemServer && !string.IsNullOrWhiteSpace(_demJobId))
                return BuildDemLayerUrl(_demJobId);

            if (mode == TerrainSourceMode.DemServer)
                return AddTerrainCacheBuster(NormalizeDemServerLayerUrl(_terrainUrl));

            return NormalizeLayerUrl(_terrainUrl);
        }

        private string BuildDemLayerUrl(string jobId)
        {
            if (string.IsNullOrWhiteSpace(jobId))
                return "";

            return AddTerrainCacheBuster($"{TrimTrailingSlash(_demServerUrl)}/terrain/{jobId.Trim()}/layer.json");
        }

        private static string NormalizeLayerUrl(string url)
        {
            if (string.IsNullOrWhiteSpace(url))
                return "";

            string trimmed = url.Trim();
            if (IsLayerJsonUrl(trimmed) ||
                trimmed.IndexOf("{z}", StringComparison.OrdinalIgnoreCase) >= 0)
            {
                return trimmed;
            }

            return TrimTrailingSlash(trimmed) + "/layer.json";
        }

        private static string NormalizeDemServerLayerUrl(string url)
        {
            if (string.IsNullOrWhiteSpace(url))
                return "";

            string trimmed = url.Trim();
            if (IsLayerJsonUrl(trimmed))
                return trimmed;

            if (trimmed.IndexOf("/terrain/", StringComparison.OrdinalIgnoreCase) >= 0)
                return TrimTrailingSlash(trimmed) + "/layer.json";

            return "";
        }

        private static bool IsLayerJsonUrl(string url)
        {
            int queryIndex = url.IndexOfAny(new[] { '?', '#' });
            string path = queryIndex >= 0 ? url.Substring(0, queryIndex) : url;
            return path.EndsWith(".json", StringComparison.OrdinalIgnoreCase);
        }

        private static string AddTerrainCacheBuster(string url)
        {
            if (string.IsNullOrWhiteSpace(url))
                return "";

            if (url.IndexOf("terrainVersion=", StringComparison.OrdinalIgnoreCase) >= 0)
                return url;

            char separator = url.Contains("?") ? '&' : '?';
            return $"{url}{separator}terrainVersion={TerrainRequestCacheVersion}";
        }

        private static string TrimTrailingSlash(string value)
        {
            return string.IsNullOrWhiteSpace(value) ? "" : value.Trim().TrimEnd('/');
        }

        private void SetFailed(string msg)
        {
            _demStatus = DemUploadStatus.Failed;
            _demStatusMessage = msg;
            Debug.LogError($"[TerrainSwitcher] {msg}");
        }

        [Serializable]
        private class UploadResponse
        {
            public string jobId;
            public string status;
        }

        [Serializable]
        private class StatusResponse
        {
            public string status;
            public string stage;
            public int progress;
            public int tileCount;
            public string error;
        }
    }
}
